ID:FPCO-12691; HOURS: 2; DONE: 90; separate frontend and backend code
gofynd/example-extension-javascript pull request #7
Opened 2023-04-24 09:43 UTC by meetkoriya13

2023-10-26 20:06 UTC, brijeshgajjarfynd commented on package.json
>      "fdk-extension-javascript": "git+https://github.com/gofynd/fdk-extension-javascript.git#v0.5.3",
move it to latest SDK and client version

2023-10-27 05:13 UTC, meetkoriya13 commented on package.json
>      "fdk-extension-javascript": "git+https://github.com/gofynd/fdk-extension-javascript.git#v0.5.3",
Updated

2023-10-27 12:09 UTC, vivek-gofynd commented on web/package.json
> +    "axios": "^0.27.2",
Check if we can use browser's fetch instead axios here @meetkoriya13

2023-10-27 12:09 UTC, vivek-gofynd commented on web/package.json
> +    "test": "jest --updateSnapshot --projects src --no-cache --detectOpenHandles --json --outputFile=./coverage/coverage.json"
remove test cases related dependencies @meetkoriya13

2023-10-27 12:09 UTC, vivek-gofynd commented on package.json
> +    "@gofynd/fdk-client-javascript": "1.3.5",
Check if we can remove this dependency @meetkoriya13

2023-10-27 12:09 UTC, vivek-gofynd commented on package.json
>      "eslint": "^7.32.0",
Remove this @meetkoriya13

2023-10-27 12:09 UTC, vivek-gofynd commented on app/routes/v1.router.js
>  router.get('/applications', async function view(req, res, next) {
Move this to common server.js file

2023-10-27 12:09 UTC, vivek-gofynd commented on web/package.json
> +    "axios": "^0.27.2",
remove this dependency @meetkoriya13

2023-10-27 12:57 UTC, vivek-gofynd requested changes
Also delete healthz routes and dotenv dependency from backend.

2023-10-27 15:31 UTC, meetkoriya13 commented on web/package.json
> +    "axios": "^0.27.2",
@vivek-gofynd  Replaced with fetch.
However, there was an interceptor for sending `x-company-id` to fetch session at the backend. as fetch does not provide functionality like an interceptor. Currently sending headers API level only.
Let me know if need to revert this change.

2023-10-27 15:31 UTC, meetkoriya13 commented on web/package.json
> +    "test": "jest --updateSnapshot --projects src --no-cache --detectOpenHandles --json --outputFile=./coverage/coverage.json"
Done

2024-07-31 10:54 UTC, closed without merging